apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-catalog-app
  template:
    metadata:
      labels:
        app: books-catalog-app
    spec:
      containers:
      - name: bookscatalog-app
        image: sit722week7part3.azurecr.io/book-catalog
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: postgresql://book_inventory_user:ZKvfpDLKgYeEOd4SfCZ8XzDrYdYW9vjy@dpg-crd60n3tq21c73cu0rm0-a.oregon-postgres.render.com/book_inventory
---
apiVersion: v1
kind: Service
metadata:
  name: books-catalog-service
spec:
  selector:
    app: books-catalog-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the Service
      targetPort: 8000  # The port the container listens on

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management-app
  template:
    metadata:
      labels:
        app: inventory-management-app
    spec:
      containers:
      - name: inventorymanagement-app
        image: sit722week7part3.azurecr.io/inventory-management
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8001"
        - name: DATABASE_URL
          value: postgresql://book_inventory_user:ZKvfpDLKgYeEOd4SfCZ8XzDrYdYW9vjy@dpg-crd60n3tq21c73cu0rm0-a.oregon-postgres.render.com/book_inventory

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the Service
      targetPort: 8001  # The port the container listens on